---
kind: pipeline
name: default

clone:
  depth: 42

steps:
  - name: phpcs
    image: joomlaprojects/docker-phpcs
    commands:
      - echo $(date)
      - /root/.composer/vendor/bin/phpcs --report=full --encoding=utf-8 --extensions=php -p --standard=build/phpcs/Joomla .
      - echo $(date)

  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./tests/javascript/node_modules
      cache_key: [ DRONE_REPO_NAMESPACE, DRONE_REPO_NAME, DRONE_BRANCH, DRONE_STAGE_NUMBER ]
    volumes:
      - name: cache
        path: /cache

  - name: javascript
    image: joomlaprojects/docker-systemtests:latest
    commands:
      - echo $(date)
      - apt-get install nodejs npm
      - ln -s /usr/bin/nodejs /usr/bin/node
      - export DISPLAY=:0
      - Xvfb -screen 0 1024x768x24 -ac +extension GLX +render -noreset > /dev/null 2>&1 &
      - sleep 3
      - fluxbox  > /dev/null 2>&1 &
      - cd tests/javascript
      - npm install
      - cd ../..
      - tests/javascript/node_modules/karma/bin/karma start karma.conf.js --single-run
      - echo $(date)

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    settings:
       rebuild: true
       mount:
        - ./tests/javascript/node_modules
       cache_key: [ DRONE_REPO_NAMESPACE, DRONE_REPO_NAME, DRONE_BRANCH, DRONE_STAGE_NUMBER ]
    volumes:
      - name: cache
        path: /cache

  - name: analysis3x
    image: rips/rips-cli:1.2.1
    when:
      branch: staging
    commands:
      - export RIPS_BASE_URI='https://api.rips.joomla.org'
      - if [ $DRONE_REPO_NAMESPACE != 'joomla' ]; then echo "The analysis check only run on the main repos"; exit 0; fi
      - rips-cli rips:scan:start -a 1 -t 1 -p $(pwd) -t 1 -R -k -T $DRONE_REPO_NAMESPACE-$DRONE_BRANCH ||  { echo "Please contact the security team at security@joomla.org"; exit 1; }
    environment:
      RIPS_USERNAME:
        from_secret: RIPS_USERNAME
      RIPS_PASSWORD:
        from_secret: RIPS_PASSWORD

volumes:
- name: cache
  host:
    path: /tmp/cache

branches:
  exclude: [ l10n_* ]
---
kind: signature
hmac: f8aa0f7552eb7c32c5585668552afffadd07a23cbbc9c1bb41bfad4df6679b3c

...
